### ISSUE TITLE
 Djangocms failed in install because timezone incorrect

### ISSUE THREAD

**Issue by lukasgarcya** [nephila/djangocms-installer#291] opened 2016-09-30 13:49 UTC
I try install the Django CMS and I receive the error: ValueError: Incorrect timezone setting: local
The installation has failed.
![error djangocms](https://cloud.githubusercontent.com/assets/1985696/18993844/905ea0ba-86fb-11e6-8368-326401329cdb.png)

**Comment by yakky** [comment] 2016-10-02 18:31
@lukasgarcya commit f7995036ed36b6e494b4ea84cc8856e85fb565df should fix the issue

**Comment by lukasgarcya** [comment] 2016-10-02 20:38
I noticed that the problem is due to the installer does not display the options for installation.

**Comment by lukasgarcya** [comment] 2016-10-02 20:46
New error because the installer does not display options for installation.
![error djangocms 2](https://cloud.githubusercontent.com/assets/1985696/19023579/16969f34-88c8-11e6-91cc-8b7095508f53.png)

**Comment by yakky** [comment] 2016-10-02 21:01
From version 0.9 batch mode is the default. You can resume the wizard mode by adding -w option in the command line. What's your system timezone BTW?

**Comment by lukasgarcya** [comment] 2016-10-02 21:08
My system timezone is UTC -03:00.

**Comment by yakky** [comment] 2016-10-02 21:11
I meant the content of /etc/timezone file

**Comment by lukasgarcya** [comment] 2016-10-02 21:13
This file is empty.

**Comment by yakky** [comment] 2016-10-02 21:15
This is the cause of the issue, then. I will investigate tomorrow reproducing the issue with an empty file (hopefully). Thanks for the additional information

**Comment by czpython** [comment] 2016-10-02 23:48
Hi @lukasgarcya,
Just a little background regarding the no options change.

In the past, our default was for the installer to be interactive.
Based on user feedback we've realized that this can be a bit confusing to newcomers who want to get up and running quickly. As a result we've made the non-interactive option the default but you can still use get the interactive prompts by passing the `-w` flag.

**Comment by yakky** [comment] 2016-11-29 11:55
So far I've been unable to reproduce the issue
However, installer 0.9.2 ships with a workaround that should prevent any error like this fallbacking to UTC

**Comment by jbarrett1205** [comment] 2017-06-02 19:44
I had this issue today with a fresh pip install of djangocms-installer.  I traced the problem to the "tzlocal" package, which attempts to determine the local timezone.  The tzlocal.get_localzone() function for *nix systems goes through a series of checks to try to find the timezone setting.  For my system, which is running Fedora 20, the method it fell back to was to look at the path of "/etc/localtime", which is apparently usually a symlink on systemd-based systems.  On my system it was not a symlink, but rather a copy of the zoneinfo file from /usr/share/zoneinfo, so it could not find a timezone from the path data and was therefore falling back to a timezone called "local", which gets stuffed into the "settings.py" file that djangocms creates.  django's manage.py then pukes on the "local" setting of the timezone since it does not exist in /usr/share/zoneinfo.  So, if you're having problems with the timezone, check the search order out for tzlocal.get_localzone() function out for your platform.  I fixed the problem for my platform by replacing the /etc/localtime file with a symlink to the correct file in /usr/share/zoneinfo, but the problem seems like it could also be fixed temporarily by setting the "TZ" env variable to the correct timezone.

**Comment by yakky** [comment] 2017-06-03 15:24
@jbarrett1205 as a workaround you can also use the "timezone" parameter https://djangocms-installer.readthedocs.io/en/latest/reference.html#wizard-arguments to provide a specific timezone, ignoring the autodetection

**Comment by yakky** [comment] 2017-07-15 10:38
I'm closing this.
djangocms installer provides:
* a command line argument to force a specific timezone (http://djangocms-installer.readthedocs.io/en/latest/reference.html#wizard-arguments)
* fallbacks to ``UTC`` if cannot discover local timezone

**Closed by yakky** 2017-07-15 10:38 UTC
